module.exports = {
  sidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started'
        },
      ],
    },
    {
      type:'category',
      label:'Plugins',
      items:[{type:'autogenerated', dirName: 'plugins'}]
    },
    'using-docker'
  ],
};