module.exports = {
  sidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started'
        },
      ],
    },
    'post-types',
    {
      type:'category',
      label:'Ajax',
      items:[{type:'autogenerated', dirName: 'ajax'}],
      collapsed: false,
    },
    {
      type:'category',
      label:'REST API',
      items:[{type:'autogenerated', dirName: 'rest-api'}],
      collapsed: false,
    },
    {
      type:'category',
      label:'Optional Services',
      items:[{type:'autogenerated', dirName: 'plugins'}],
      collapsed: true,
    },
    'using-docker'
  ],
};